# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/file/project/vivado/cpu/cpu.srcs/sources_1/ip/data_sram/data_sram.xci
# IP: The module: 'data_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/file/project/vivado/cpu/cpu.srcs/sources_1/ip/data_sram/data_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_sram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/file/project/vivado/cpu/cpu.srcs/sources_1/ip/data_sram/data_sram.xci
# IP: The module: 'data_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/file/project/vivado/cpu/cpu.srcs/sources_1/ip/data_sram/data_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_sram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
